In [6]:
from product_sub.infrastructure.dataset_builder import DatasetBuilder 
from product_sub.domain.feature_creator import CategoricalCreatorFromNumerical

In [7]:
from pandas_profiling import ProfileReport
from sklearn.pipeline import Pipeline

In [8]:
data = DatasetBuilder("data.csv", "socio_eco.csv").create_dataset()
profile = ProfileReport(data, title='Pandas Profiling Report', explorative=True)

In [9]:
profile.to_widgets()

HBox(children=(HTML(value='Summarize dataset'), FloatProgress(value=0.0, max=34.0), HTML(value='')))

HBox(children=(HTML(value='Generate report structure'), FloatProgress(value=0.0, max=1.0), HTML(value='')))

HBox(children=(HTML(value='Render widgets'), FloatProgress(value=0.0, max=1.0), HTML(value='')))

VBox(children=(Tab(children=(Tab(children=(GridBox(children=(VBox(children=(GridspecLayout(children=(HTML(valuâ€¦

In [28]:
%run ../product_sub/domain/feature_creator.py

JOB_TYPE                0
STATUS                  0
EDUCATION               0
CONTACT                 0
RESULT_LAST_CAMPAIGN    0
is_first_campaign       0
dtype: int64

TypeError: Some of the variables are not categorical. Please cast them as object before calling this transformer

In [23]:
test3.shape

(43330, 26)

In [26]:
test2

,AGE,HAS_DEFAULT,BALANCE,HAS_HOUSING_LOAN,HAS_PERSO_LOAN,DURATION_CONTACT,NB_CONTACT,NB_DAY_LAST_CONTACT,NB_CONTACT_LAST_CAMPAIGN,SUBSCRIPTION,EMPLOYMENT_VARIATION_RATE,IDX_CONSUMER_PRICE,IDX_CONSUMER_CONFIDENCE,MONTH,WEEKDAY,is_first_campaign,nb_contact_last_campaign_inf_4,nb_contact_last_campaign_inf_8,nb_contact_last_campaign_inf_12,nb_contact_last_campaign_sup_12
0,58,0,2143,1,0.0,261,1,-1,0,0,1.1,93.994,-36.4,5,0,1,0,0,0,0
1,33,0,2,1,1.0,76,1,-1,0,0,1.1,93.994,-36.4,5,0,1,0,0,0,0
2,47,0,1506,1,0.0,92,1,-1,0,0,1.1,93.994,-36.4,5,0,1,0,0,0,0
3,33,0,1,0,0.0,198,1,-1,0,0,1.1,93.994,-36.4,5,0,1,0,0,0,0
4,35,0,231,1,0.0,139,1,-1,0,0,1.1,93.994,-36.4,5,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43325,47,0,0,0,0.0,508,1,-1,0,1,-1.1,94.601,-49.5,10,2,1,0,0,0,0
43326,61,0,1058,0,0.0,277,1,92,5,0,-1.1,94.601,-49.5,10,2,0,0,1,0,0
43327,24,0,822,0,0.0,184,1,91,2,1,-1.1,94.601,-49.5,10,2,0,1,0,0,0
43328,70,0,0,0,0.0,258,1,92,5,1,-1.1,94.601,-49.5,10,2,0,0,1,0,0
43329,53,0,1294,0,0.0,71,1,-1,0,0,-1.1,94.601,-49.5,10,3,1,0,0,0,0

In [27]:
test

,JOB_TYPE,STATUS,EDUCATION,CONTACT,RESULT_LAST_CAMPAIGN,is_first_campaign
0,Manager,Marie,Tertiaire,Autre,premier_contact,1
1,Entrepreuneur,Marie,Secondaire,Autre,premier_contact,1
2,Col bleu,Marie,Autre,Autre,premier_contact,1
3,Autre,Celibataire,Autre,Autre,premier_contact,1
4,Manager,Marie,Tertiaire,Autre,premier_contact,1
...,...,...,...,...,...,...
43325,Manager,Marie,Tertiaire,Portable,premier_contact,1
43326,Retraite,Marie,Secondaire,Portable,Succes,0
43327,Etudiant,Celibataire,Secondaire,Portable,Echec,0
43328,Retraite,Marie,Secondaire,Portable,Succes,0
43329,Col bleu,Marie,Primaire,Autre,premier_contact,1